# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


target 'iddc-oc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iddc-oc
  # pod 'iddc', '0.1.85'
  pod 'iddc-xcode9.3', '0.1.100'

  target 'iddc-ocTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iddc-ocUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
